# Use a Node.js base image
FROM node:20-alpine

# Set the working directory in the container
RUN mkdir -p /home/node/app &&\
    chown -R node:node /home/node/app
WORKDIR /home/node/app

RUN chgrp -R 0 /home/node/app &&\
    chmod -R g+rwX /home/node/app

COPY package*.json /home/node/app/
USER 1000
RUN npm install


# RUN addgroup --system --gid 1001 nodejs
# RUN adduser --system --uid 1001 nextjs

# RUN mkdir .next
# RUN chown nextjs:nodejs .next

# ENV NEXT_PUBLIC_API="http://localhost:8000"

COPY --chown=node:node . /home/node/app
RUN npm run build
EXPOSE 3000
CMD ["npm", "run", "start"]
