# Use a Node.js base image

FROM node:20-alpine

# Set the working directory in the container

WORKDIR /src

# Copy package.json and package-lock.json to the working directory

COPY package.json package-lock.json /src/

RUN apk --no-cache add curl

# Install dependencies

RUN npm install

# Copy all files from the current directory to the working directory

COPY . .

# Expose the port the app runs on

EXPOSE 3000

# Define the command to start the app

CMD ["npm", "run","dev"]
