FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
COPY . /src
WORKDIR /src
RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"
RUN dotnet build "clinic-reservation.csproj" -c Release -o /app/build

FROM build AS final
WORKDIR /src
COPY --from=build /app/build .
EXPOSE 5243
ENTRYPOINT [ "dotnet","ef database update","&&","dotnet","run" ]

# docker pull mcr.microsoft.com/dotnet/sdk

#"dotnet","ef database update","&&",