FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
EXPOSE 5243
EXPOSE 8080
COPY . /src
WORKDIR /src
RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"
ENV ASPNETCORE_URLS=http://+:5243
ENV ASPNETCORE_ENVIRONMENT=”development”


# ENTRYPOINT [ "dotnet ef database update; dotnet run" ]

# docker pull mcr.microsoft.com/dotnet/sdk

#"dotnet","ef database update","&&",